[workspace]
authors = ["Juan C. Villada <jvillada@lbl.gov>"]
channels = ["conda-forge"]
name = "radarsci"
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
version = "0.1.0"

[tasks.radarsci]
cmd = "python -m radarsci"
env = { PYTHONPATH = "src" }

[dependencies]
python = ">=3.11,<3.13"
typer = ">=0.12"
httpx = ">=0.26"
beautifulsoup4 = ">=4.12"
rich = ">=13.7"
lxml = ">=4.9"
